version: "3.9"
services:
  app-spring:
    build: .
    depends_on:
      - mysql-spring
    ports:
      - "8080:8080"
    links:
      - mysql-spring
  mysql-spring:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
 