GET http://localhost:8080/api/accounts/all
###
GET http://localhost:8080/api/accounts/search/1

###
PATCH http://localhost:8080/api/accounts/all
###
POST http://localhost:8080/api/accounts/save
Content-Type: application/json

{
    "username":"SantiGomez@gmail.com",
    "password":"messi10crack",
    "amount": 31500,
    "user":{}
}