GET http://localhost:8080/accounts
Content-Type: application/json
###
POST http://localhost:8080/accounts/44
Content-Type: application/json

{
    "username":"michaelJson@gmail.com",
    "password":"aiugoki",
    "amount": 24000,
    "user":{}
}
###
GET http://localhost:8080/accounts/get/2