GET http://localhost:8080/accounts
Content-Type: application/json
###
GET http://localhost:8080/accounts/2
Content-Type: application/json
###
POST http://localhost:8080/accounts/3
Content-Type: application/json

{
    "username":"SantiGomez@gmail.com",
    "password":"messi10crack",
    "amount": 31500,
    "user":{}
}
###
GET http://localhost:8080/accounts/get/2