POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

    {
        "name": "Pedro",
        "lastname": "Dominguez",
        "age": 50
    }
###
GET http://localhost:8080/users
Content-Type: application/json
###
GET http://localhost:8080/users/2
Content-Type: application/json
###
GET http://localhost:8080/users/generate/1
Content-Type: application/json
###
GET http://localhost:8080/users/generate
Content-Type: application/json
###
POST http://localhost:8080/users/create-account/2
###
DELETE http://localhost:8080/users/7 HTTP/1.1
