POST http://localhost:8080/api/users/save HTTP/1.1
Content-Type: application/json

    {
        "name": "Pedro",
        "lastname": "Dominguez",
        "age": 50
    }
###
GET http://localhost:8080/api/users/all

###
GET http://localhost:8080/api/users/search/4

###
GET http://localhost:8080/api/users/generate/one
Content-Type: application/json
###
GET http://localhost:8080/api/users/generate/5
Content-Type: application/json
###
POST http://localhost:8080/api/users/create-account/2
Content-Type: application/json

{
    "username": "yo",
    "password": "password",
    "amount": {{$randomInt 10000 50000}},

}
###
DELETE http://localhost:8080/users/7 HTTP/1.1
